markdown: redcarpet
highlighter: pygments
permalink: /:title/
url: http://iceway.github.io/
name: L&Z
description: Iceway [ Bit by bit, step by step. ]
author: iceway
email: iceway.zhang@gmail.com
safe: true
paginate: 100
about: "coder"

redcarpet:
        extensions:
                - fenced_code_blocks
                - no_intra_emphasis
                - strikethrough
                - autolink
                - tables
