permalink: /:year/:month/:day/:title.html
paginate: 30
markdown: redcarpet
highlighter: pygments

redcarpet:
  extensions:
    - fenced_code_blocks
    - no_intra_emphasis
    - strikethrough
    - autolink
    - tables

# 作者
author:
  name: Iceway Zhang
  email: iceway.zhang@gmail.com
  github: http://github.com/iceway

# 站点
site:
  title: L&Z
  description: Iceway's Sharing and Recording.
  url: http://iceway.github.io/
  favicon: /public/images/favicon.ico
  logo: /public/images/logo.png

# 本地化
locals:
  home: 首页
  tag: 标签
  category: 分类
  about: 关于

# jekyll(>=3.0) 要求使用paginate必须在config中显式声明
gems:
  - jekyll-paginate
